version: "3.9"

services:
  nginx:
    build: ./nginx.dev
    volumes:
      - static:/static
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      - static:/backend/static
    ports:
      - "8000:8000"

volumes:
  static:
